import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer";
import Newsletter from "@/components/newsletter";
import { Providers } from "@/app/provider";
import Outreach from "@/components/outreach";
// import Bible from "@/components/biblestudies";
import Wall from "@/components/wall";
import Aboutus from "@/components/aboutus";
import Gallery from '@/components/gallery'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <Wall />
          <Aboutus />
          <Outreach />
          <Newsletter></Newsletter>
          <Gallery />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
